export const CORS_WHITELIST_URLS = "CORS_WHITELIST_URLS";

export const PORT = "PORT";

export const DB_HOST = "TYPEORM_DATABASE_HOST";
export const DB_PORT = "TYPEORM_DATABASE_PORT";
export const DB_USERNAME = "TYPEORM_DATABASE_USERNAME";
export const DB_PASSWORD = "TYPEORM_DATABASE_PASSWORD";
export const DB_NAME = "TYPEORM_DATABASE_NAME";

export const NODE_ENV = "NODE_ENV";

export const MAILJET_API_KEY = "MAILJET_API_KEY";
export const MAILJET_SECRET_KEY = "MAILJET_SECRET_KEY";
export const MAILJET_NOREPLY_ADDRESS = "MAILJET_NOREPLY_ADDRESS";

export const JWT_SECRET = "JWT_SECRET";

export const CLOUDINARY_CLOUD_NAME = "CLOUDINARY_CLOUD_NAME";
export const CLOUDINARY_API_KEY = "CLOUDINARY_API_KEY";
export const CLOUDINARY_API_SECRET = "CLOUDINARY_API_SECRET";

export const PAYPAL_CLIENT_ID = "PAYPAL_CLIENT_ID";
export const PAYPAL_SECRET = "PAYPAL_SECRET_KEY";
export const PAYPAL_BASE_URL = "PAYPAL_BASE_URL";

export const CLIENT_BASE_URL = "CLIENT_BASE_URL";
export const TRANSLATOR_BASE_URL = "TRANSLATOR_BASE_URL";
export const DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID";
export const DISCORD_SECRET_KEY = "DISCORD_SECRET_KEY";
export const DISCORD_AUTHORIZATION_LINK = "DISCORD_AUTHORIZATION_LINK";
export const DISCORD_REDIRECT_URI = "DISCORD_REDIRECT_URI";

export const GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID";
export const GOOGLE_SECRET_KEY = "GOOGLE_SECRET_KEY";
export const GOOGLE_REDIRECT_URI = "GOOGLE_REDIRECT_URI";

export const ADMIN_MASTER_KEY = "ADMIN_MASTER_KEY";

export const DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN";
